#pragma once

#include <vector>
#include <string>

enum class SCRIPT_TYPE
{
	BATTLEPHASESCRIPT,
	CAMERASCRIPT,
	CRUSADERSCRIPT,
	CULTISTBRAWLERSCRIPT,
	CULTISTWITCHSCRIPT,
	DOORSCRIPT,
	EFFECTSCRIPT,
	HIGHWAYMANSCRIPT,
	HPBARSCRIPT,
	ITEMMANAGERSCRIPT,
	ITEMSCRIPT,
	LIGHTBARSCRIPT,
	LIGHTSCRIPT,
	MADMANSCRIPT,
	PARTYICONSCRIPT,
	PEWLARGESCRIPT,
	PEWMEDIUMSCRIPT,
	PEWSMALLSCRIPT,
	PLAGUEDOCTORSCRIPT,
	SKELETONARBALISTSCRIPT,
	SKELETONCOMMONSCRIPT,
	SKELETONCOURTIERSCRIPT,
	SKELETONDEFENDERSCRIPT,
	SKILLBUTTONSCRIPT,
	SLOTSCRIPT,
	STOREITEMSCRIPT,
	TEXTUISCRIPT,
	TOWNOBJECTSCRIPT,
	UISCRIPT,
	VESTALSCRIPT,
	WALLSCRIPT,
	END,
};

using namespace std;

class Script;

class ScriptManager
{
public:
	static void GetScriptInfo(vector<wstring>& _vector);
	static Script * GetScript(const wstring& _scriptName);
	static Script * GetScript(UINT _scriptType);
	static const wchar_t * GetScriptName(Script * _script);
};
